blank_issues_enabled: false
contact_links:
  - name: 💬 `#electron` Channel on Discord
    url: https://discord.gg/ZKfhzk8dQh
    about: Interact with others using remix-electron, and ask support questions.
